.PHONY: clean All

All:
	@echo "----------Building project:[ TP2 - Debug ]----------"
	@cd "/users/info/etu-s4/renardn/m4105C_projet/M4105C/TP2" && "$(MAKE)" -f  "TP2.mk"
clean:
	@echo "----------Cleaning project:[ TP2 - Debug ]----------"
	@cd "/users/info/etu-s4/renardn/m4105C_projet/M4105C/TP2" && "$(MAKE)" -f  "TP2.mk" clean
